apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-workspace-ingress
  namespace: swe-ai-fleet
  labels:
    app: minio-workspace
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-r53
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - minio-console.underpassai.com
      secretName: minio-console-tls
  rules:
    - host: minio-console.underpassai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-workspace-console-svc
                port:
                  name: console
