apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-minio-from-workspace-services
  namespace: minio-workspace
  labels:
    app: minio-workspace
spec:
  podSelector:
    matchLabels:
      app: minio-workspace
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              access-minio-workspace: "true"
      ports:
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 9001
