apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swe-fleet
  namespace: swe
spec:
  ingressClassName: nginx
  rules:
    - host: swe-ai-fleet.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-frontend
                port:
                  number: 8080
    - host: demo.swe-ia-fleet.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-frontend
                port:
                  number: 8080


